// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  //app
  wheel: require('../Images/App/wheel.png'),
  wheel1: require('../Images/App/wheel1.png'),
  settings: require('../Images/App/settings.png'),
  sound: require('../Images/App/music.png'),
  language: require('../Images/App/global.png'),
  select_background: require('../Images/App/select_background.png'),
  introduce: require('../Images/App/information.png'),
  help: require('../Images/App/question.png'),
  other_app: require('../Images/App/apps.png'),
  play: require('../Images/App/play.png'),
  add: require('../Images/App/plus.png'),
  minus: require('../Images/App/minus.png'),
  not_mute: require('../Images/App/sound.png'),
  mute: require('../Images/App/mute.png'),
  vn: require('../Images/App/vietnam.png'),
  us: require('../Images/App/usa.png'),
  settings1: require('../Images/App/pencil.png'),
  background1: require('../Images/App/background1.png'),
  background2: require('../Images/App/background6.png'),
  background3: require('../Images/App/background7.png'),
  logo_wheel: require('../Images/App/Logo_wheel.png')
}

export default images
